### ISSUE TITLE
Changing "Frame counter checks" setting causes Device Address change

### ISSUE THREAD

**Issue by Paul-B** [TheThingsNetwork/ttn#373]
This is a bug report for v2-preview.

- Explain what you want to do
Toggle the ""Frame counter checks" setting
- Explain what steps you took
Did that a couple of times
- Explain what went wrong or what is missing\
Found out that my Device Address has changed two a new value two times

## Environment

- `ttn version` returns: `Commit={...}`
- `ttnctl version` returns: `Commit={...}`
- My application:
  - App ID: `{sodaq_testing}`
- My gateway:
  - EUI: `{...}`
  - Connected to: `router.{...}.thethings.network:1700`
- My node:
  - Device ID: `{jpmtesting}`
  - AppEUI: `{70B3D57EF0000187}`
  - DevEUI: `{00E082F13BD06420}`
- MQTT is connected to: `{...}.thethings.network:{1883/8883}`

**Comment by romeovs** [comment]
Fixed in the console! @Paul-B can you check this and close the issue if you agree?

**Comment by Paul-B** [comment]
It still happens here. I don't know if you could confirm the bug but maybe I should double check if what I'm seeing is intended behavior.

**Comment by romeovs** [comment]
Does this happen for OTAA devices or ABP devices?

**Comment by Paul-B** [comment]
After trying again a couple of times I can confirm that the bug has been fixed. I must have still had the old version in my browser cache.

**Comment by romeovs** [comment]
Okay cool!

**Comment by vikram-kadian** [comment]
Same happened, my device id changed when i enabled the frame counter checks from android app of ttn.

**Comment by htdvisser** [comment]
We don't have an official Android app. Any Android or iOS apps are developed independently of TTN, so you'll have to contact the developer of those apps to get this solved.

**Comment by vikram-kadian** [comment]
Oh! ok i see, have installed this app : https://play.google.com/store/apps/details?id=com.async.ttn&hl=en, and now have to reprogram my nodes to match the device address ABP :(

**Comment by johanstokking** [comment]
@vikram-kadian yep, that's a community app, not developed by the core team.
