### ISSUE TITLE
Estimated airtime in TTN Console's gateway traffic and application/device data do not match

### ISSUE THREAD

**Issue by avbentem** [TheThingsNetwork/ttn#646]
This is a **bug report** for **the console**.

> What do you want to do?

Get the correct estimated airtime of a packet in TTN Console.

> What steps did you take?

Sent a 21 bytes packet (8 bytes application payload) on SF7. For this, the LoRaWAN air time calculation sheet at https://www.thethingsnetwork.org/forum/t/spreadsheet-for-lora-airtime-calculation/1190 shows 56.576 ms airtime. Also, the gateway's traffic page shows: "airtime (ms) = 56.6 ms".

(When repeating with 17 bytes total, being 4 bytes application payload, the sheet calculates 51.456 ms, and the gateway then shows 51.5 ms too.)

> What went wrong or what is missing?

For 21 bytes, the application's and device's data pages show "Estimated Airtime = **51**.456 ms" instead of **56**.5 ms like the gateway does. 

**It seems 2 bytes too few are taken into account for the estimation?** For 19 bytes, the calculation sheet indeed shows 51.456 ms.

(When repeating with 17 bytes, the application and device data show 46.336 ms, while the gateway shows 51.5 ms. Again: like 2 bytes fewer were used for the calculations, as for 15 bytes the sheet indeed shows 46.336.)

> Do you have Screenshots?

Gateway:

![image](https://user-images.githubusercontent.com/1497002/27771667-c2f96ae2-5f53-11e7-91a3-257cc109d09f.png)

Device:

![image](https://user-images.githubusercontent.com/1497002/27771673-f195212a-5f53-11e7-8b7c-f7e7b9148ebb.png)

...after scrolling down:

![image](https://user-images.githubusercontent.com/1497002/27771679-13da11b4-5f54-11e7-821c-6e67fe5e99b1.png)

Airtime calculator:

![image](https://user-images.githubusercontent.com/1497002/27771712-a6f6eaf8-5f54-11e7-94f5-4518fecbbfe1.png)

> What kind of OS/Browser/Gateway are you using? Which version?

Mac OS X, Chrome, single-channel test gateways.

> What are the IDs and EUIs of your Device/Gateway? (if applicable)

- Gateways: eui-b827ebffff5fe05c and eui-5ccf7ff42f1970ec
- Device: arjanvanb-bb-2/EUI 0004A30B001B1874

> What do your configuration files look like?

n/a

> What do your log files look like?

n/a

> Can you fix this yourself and submit a pull request?

Maybe, if you open source the code ;-)

**Comment by romeovs** [comment]
@jpmeijers Can you have a look why this is wrong?

**Comment by johanstokking** [comment]
Isn't this fixed @Ragnn @romeovs ?

**Comment by romeovs** [comment]
Not yet. I'll work on it soon. @Ragnn added the backend part, but the front-end needs to be updated to reflect that.

**Comment by romeovs** [comment]
This should be fixed by fe151b7f53. Can you confirm @avbentem?

**Comment by htdvisser** [comment]
@romeovs: This issue is still not resolved (as far as I can see on the PCN console).

Take as an example the `office-app`. Our sensor at HQ should show an airtime of `51.456`. The gateway view shows the correct value, but the Data view doesn't. 

Today I started with the implementation of #682, which adds the airtime to uplink (and downlink event) metadata. When deployed, that value can be displayed in the console.

**Comment by romeovs** [comment]
The estimated airtime shown in the console is calculated by the `github.com/TheThingsNetwork/ttn/utils/toa` package. Could it be that the parameters are interpreted wrongfully?

**Comment by htdvisser** [comment]
Both values are calculated by the console. One is correct, another isn't.

<img width="855" alt="screen shot 2017-11-09 at 12 12 08" src="https://user-images.githubusercontent.com/181308/32602689-5b800a1a-c547-11e7-9056-a3b6a34e4bd4.png">

**Comment by romeovs** [comment]
Coule it be that the console gives the wrong parameters to the `toa` package? https://github.com/TheThingsIndustries/console/blob/master/server/api/events/app_subscription.go#L302-L305

Difference between PHY payload and application payload could be the cause?

**Comment by htdvisser** [comment]
Likely. In that case it can be resolved when https://github.com/TheThingsNetwork/ttn/commit/0f795e39c6f00b663f70212595de09cf4f2c92a4 is live

**Comment by sigmaroot** [comment]
Is this still unsolved? I'm seeing some differences and I think both, gateway and application estimated airtimes are wrong.

Sending 38 byte of app payload, resulting in 51 byte payload in the gateway overview:

![grafik](https://user-images.githubusercontent.com/13609443/45381681-4b0cf700-b606-11e8-8c85-00d6718e4c45.png)

In the application:

![grafik](https://user-images.githubusercontent.com/13609443/45381739-7abbff00-b606-11e8-847b-fc38158bfc68.png)

And this is calculated with the Semtech LoRa Model Calculator Tool (51 bytes):

![grafik](https://user-images.githubusercontent.com/13609443/45381795-a2ab6280-b606-11e8-9027-284a413803ae.png)

And with 38 bytes:

![grafik](https://user-images.githubusercontent.com/13609443/45381887-e605d100-b606-11e8-8347-7fe60434037c.png)

So, we do have 4 different airtimes, none matching the TTN airtimes.

Which one is the correct one?

**Comment by kizniche** [comment]
I recently had The Things Network stop the movement of all my data from my gateway to my apps due to going over the 30-second daily limit (not just the offending app/device, but ***all*** of my apps, even the ones not exceeding 30 seconds/day). This was due to using the App airtime estimate. Using the gateway airtime, data began appearing in my apps again. I see reporting incorrect airtime (or calculation) as a significant bug.

Additionally, is it expected behavior for data from all apps to cease operating when one device exceeds the daily transmission limit?

**Comment by htdvisser** [comment]
Hi @kizniche, the 30-second daily limit is not enforced; we don't even have any code to do that, so I can with 100% certainty say that the lack of traffic was not caused by this.

**Comment by kizniche** [comment]
Thank you for the clarification. Perhaps it's just a coincidence they all stopped. I'll have to investigate further.
